# Generated by Django 6.0.1 on 2026-01-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Denomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Typologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndegpoi', models.PositiveIntegerField(unique=True)),
                ('type_de_reconnaissance_patrimoniale', models.CharField(blank=True, max_length=255, null=True)),
                ('departement', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('commune', models.CharField(blank=True, max_length=255, null=True)),
                ('code_insee', models.IntegerField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=500, null=True)),
                ('references_cadastrales', models.CharField(blank=True, max_length=255, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('informations_d_acces_en_transport_en_commun', models.TextField(blank=True, null=True)),
                ('statut_de_la_propriete_actuelle', models.CharField(blank=True, max_length=255, null=True)),
                ('proprietaire', models.CharField(blank=True, max_length=255, null=True)),
                ('appellation', models.CharField(blank=True, max_length=255, null=True)),
                ('concepteur_s', models.TextField(blank=True, null=True)),
                ('entrepreneur_s', models.TextField(blank=True, null=True)),
                ('autre_s_intervenant_s', models.TextField(blank=True, null=True)),
                ('maitre_s_d_ouvrage', models.TextField(blank=True, null=True)),
                ('datation', models.CharField(blank=True, max_length=255, null=True)),
                ('periode_de_construction', models.CharField(blank=True, max_length=255, null=True)),
                ('historique_et_description', models.TextField(blank=True, null=True)),
                ('protection_ou_label', models.CharField(blank=True, max_length=255, null=True)),
                ('precisions_sur_la_protection', models.TextField(blank=True, null=True)),
                ('sources_d_archives', models.TextField(blank=True, null=True)),
                ('sources_documentaires', models.TextField(blank=True, null=True)),
                ('references_bibliographiques', models.TextField(blank=True, null=True)),
                ('justification', models.CharField(blank=True, max_length=255, null=True)),
                ('credits', models.CharField(blank=True, max_length=255, null=True)),
                ('url_image', models.URLField(blank=True, null=True)),
                ('dates_de_reference', models.ManyToManyField(blank=True, related_name='sites', to='www.datereference')),
                ('denominations', models.ManyToManyField(blank=True, related_name='sites', to='www.denomination')),
                ('typologies', models.ManyToManyField(blank=True, related_name='sites', to='www.typologie')),
            ],
        ),
    ]
