# Generated by Django 6.0.1 on 2026-01-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='adresse_com',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='site_olympique',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
